### ISSUE TITLE
appsec-create not working

### ISSUE THREAD

**Issue by kusum008** [akamai/cli-onboard#33]
[onboard.log](https://github.com/akamai/cli-onboard/files/12051062/onboard.log)
[appsec-create-by-hostname.csv](https://github.com/akamai/cli-onboard/files/12051064/appsec-create-by-hostname.csv)

**Command:**
`akamai onboard -a B-V-4MQDJAT -s automation appsec-create -c ctr_V-4MQDJBG -g 238528 --csv sample_templates/appsec-create-by-hostname.csv --by hostname --activate staging --email kmanjuna@akamai.com  `

**Error:**
`ERROR  : {"type":"https://problems.luna.akamaiapis.net/appsec-configuration/error-types/UNAUTHORIZED","status":403,"title":"Unauthorized Access/Action","detail":"You don't have access to the contract and group.","instance":"https://problems.luna.akamaiapis.net/appsec-configuration/error-instances/845864b042f04383"}
Traceback (most recent call last):
  File "/Users/kmanjuna/.akamai-cli/src/cli-onboard/bin/akamai-onboard.py", line 1004, in <module>
    status = cli(prog_name='akamai onboard')
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/kmanjuna/.akamai-cli/src/cli-onboard/bin/akamai-onboard.py", line 901, in appsec_create
    _, selectable_hostnames, selectable_df = wrap_api.get_selectable_hostnames(contract_id[4:], group_id[4:], appsec_main.network)
  File "/Users/kmanjuna/.akamai-cli/src/cli-onboard/bin/wrapper_api.py", line 686, in get_selectable_hostnames
    return response, hostnames, selectable_df
√ DevReadiness/CLIOnboarding % akamai onboard -a B-V-4MQDJAT -s automation appsec-create -c ctr_V-4MQDJBG -g grp_238528 --csv sample_templates/appsec-create-by-hostname.csv  --activate staging --email kmanjuna@akamai.com
/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

INFO   : Start Akamai CLI onboard
WARNING: Account Name: Advanced Technical Training – Automation & Bulk Onboarding_Direct Customer B-V-4MQDJAT
√ DevReadiness/CLIOnboarding % akamai onboard -a B-V-4MQDJAT -s automation appsec-create -c ctr_V-4MQDJBG -g grp_238528 --csv sample_templates/appsec-create-by-hostname.csv  --activate staging --email kmanjuna@akamai.com
/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

INFO   : Start Akamai CLI onboard
WARNING: Account Name: Advanced Technical Training – Automation & Bulk Onboarding_Direct Customer B-V-4MQDJAT
Traceback (most recent call last):
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'configNameInProduction'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kmanjuna/.akamai-cli/src/cli-onboard/bin/akamai-onboard.py", line 1004, in <module>
    status = cli(prog_name='akamai onboard')
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/kmanjuna/.akamai-cli/src/cli-onboard/bin/akamai-onboard.py", line 901, in appsec_create
    _, selectable_hostnames, selectable_df = wrap_api.get_selectable_hostnames(contract_id[4:], group_id[4:], appsec_main.network)
  File "/Users/kmanjuna/.akamai-cli/src/cli-onboard/bin/wrapper_api.py", line 677, in get_selectable_hostnames
    selectable_df = df[(df['activeInStaging']) & (df['configNameInProduction'].isnull())]
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/pandas/core/frame.py", line 3760, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/kmanjuna/.akamai-cli/venv/cli-onboard/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'configNameInProduction' `

**Comment by pwongcha** [comment]
Thank you for reporting the issue @kusum008.  I can replicate the issue.
